### PR TITLE
feat: upgrade go-github to v52

### PR DESCRIPTION
**Pull request by marcelosousa**
This pull request upgrades the go-github dependency from v50 to v52.

### CODE REVIEW

**Comment by migueleliasweb** [comment]
Thanks for the PR, @marcelosousa . I will have a look at it 👍 .

**Comment by quike** [comment]
@migueleliasweb I am interested in this change as well as I would like to update some projects to https://github.com/palantir/go-githubapp/releases/tag/v0.16.0 but cannot until this change , any chance to move it forward? thanks!

**Review by quike — APPROVED** [review]

**Comment by marcelosousa** [comment]
@migueleliasweb it would be nice if you could install Reviewpad (https://reviewpad.com/) in this repo to automatically merge PRs once they are approved. Of course, you're the maintainer of the repo and IMO there's no reason to keep this PR on hold for a week for such a minor change. Bottom line: we shouldn't bother you with such PRs.

**Comment by migueleliasweb** [comment]
> @migueleliasweb it would be nice if you could install Reviewpad (https://reviewpad.com/) in this repo to automatically merge PRs once they are approved. Of course, you're the maintainer of the repo and IMO there's no reason to keep this PR on hold for a week for such a minor change. Bottom line: we shouldn't bother you with such PRs.

I've never used that. I will consider it! 👍

**Comment by migueleliasweb** [comment]
Merged and new release created :)

**Pull request merged**
