### PR TITLE
Add alpha support for Github enterprise

### PR DESCRIPTION
**Pull request by migueleliasweb**

### CODE REVIEW

**Review by atkinsonm — APPROVED** [review]
Looks great! Thanks for the quick turnaround 🎉

**Comment by migueleliasweb** [comment]
@atkinsonm could you confirm that this approach works for you? Could you please test this branch on your code?

**Comment by atkinsonm** [comment]
Apologies for the delay. I did confirm that this version works and saves me from having to build the endpoint pattern myself 🙌

**Comment by migueleliasweb** [comment]
I will create a release later today.

**Pull request merged**
