### PR TITLE
Add edge case mutation for Repositories.GetContents()

### PR DESCRIPTION
**Pull request by migueleliasweb**

### CODE REVIEW

**Comment by migueleliasweb** [comment]
Addresses https://github.com/migueleliasweb/go-github-mock/issues/26

**Comment by LeoQuote** [comment]
I just tested this branch and all looks good

**Comment by migueleliasweb** [comment]
I will see if I can release an alpha version for now so at least you can pin a release.

**Comment by LeoQuote** [comment]
It's ok to me , I just get rid of the `/` in path to avoid this issue

**Comment by migueleliasweb** [comment]
Closing in favor of https://github.com/migueleliasweb/go-github-mock/pull/30

**Pull request closed without merging**
