### PR TITLE
feat(deps): update go-github to v60

### PR DESCRIPTION
**Pull request by quike**
https://github.com/google/go-github/releases/tag/v60.0.0
[CHANGELOG](https://github.com/google/go-github/compare/v59.0.0...v60.0.0)

Extra:
- Add makefile defs with common operations.
- Update endpoints based on current version.
- Add [.editorconfig](https://editorconfig.org/) for IDE expected code style.
- Add vendors to gitignore to avoid mistakes pushing deps.

### CODE REVIEW

**Comment by quike** [comment]
@migueleliasweb any chance you could take a look? also, shall we enable github actions for pull request testing? I saw you have a PR https://github.com/migueleliasweb/go-github-mock/pull/1 but never got merged.

**Comment by migueleliasweb** [comment]
> @migueleliasweb any chance you could take a look? also, shall we enable github actions for pull request testing? I saw you have a PR #1 but never got merged. I do have a primary approach here: https://github.com/quike/go-github-mock/actions but tell me what you would like and we can build it progressively. At least I am trying to put so far build/test/lint so pr's can be verified and later add automatic semver or anything else.

That would be great to have :). I'll have a look at your implementation and we can create a separate PR to work on that.

**Comment by migueleliasweb** [comment]
I'll have a look later tonight about the changes. Thanks for the contributions :).

**Comment by quike** [comment]
@migueleliasweb any chance to take a look to this one? thanks

**Comment by quike** [comment]
> I'll have a look later tonight about the changes. Thanks for the contributions :).

Any chance to do it? Thanks

**Comment by migueleliasweb** [comment]
New release with v61 of `go-github`: https://github.com/migueleliasweb/go-github-mock/releases/tag/v0.1.

Can we close this one for now?

**Pull request closed without merging**
