### PR TITLE
Removing redeclaration of GetScimV2OrganizationsUsersByOrgByScimUserId

### PR DESCRIPTION
**Pull request by renzors**
It is already declared in line 3145

### CODE REVIEW

**Comment by migueleliasweb** [comment]
Hi @renzors ,  the file `src/mock/endpointpattern.go` is auto generated so changing it wouldn't yield much result.

The ideal fix would be fixing the `gen.go` script to properly check if a given route was already created.

**Comment by migueleliasweb** [comment]
I'm working on improving the `gen.go` script and this problem should be fixed with it.

**Comment by migueleliasweb** [comment]
@renzors could you try to use the branch `fix-gen-redeclarations` and test the changes?

**Comment by renzors** [comment]
Hi @migueleliasweb, thanks for the quick review! Oh I see, I will use that branch and let you know, thanks!

**Comment by renzors** [comment]
Hi @migueleliasweb, it works perfect from `fix-gen-redeclarations` branch. Thanks!

**Comment by renzors** [comment]
Closing this PR, and waiting for the fix in the main branch :-)

**Comment by migueleliasweb** [comment]
The fix was merged. Thanks @renzors !

**Pull request closed without merging**
