### PR TITLE
upgrade to go-github v55

### PR DESCRIPTION
**Pull request by veziak**

### CODE REVIEW

**Comment by migueleliasweb** [comment]
Thanks for the contribution, @veziak , I will have a look at this later today :+1: .

**Comment by migueleliasweb** [comment]
Hi @veziak , could you (at least for this PR) not include the changes in the endpoints and run `go mod tidy` again?

**Comment by veziak** [comment]
Hi @migueleliasweb I've just removed my changes to endpointpattern.go, just a note that those changes were made when I executed the application as part of the local build, I didn't change that file manually. And 'go mod tidy' is already part of this pr.

**Comment by veziak** [comment]
Great library btw!, I don't how ppl test github apps without it :)

**Comment by quike** [comment]
@migueleliasweb Hi, any change we can get this merged? Thanks.

**Comment by migueleliasweb** [comment]
Merged and created new release, enjoy :) 

https://github.com/migueleliasweb/go-github-mock/releases/tag/v0.0.20

**Pull request merged**
