### PR TITLE
Add mutex to FIFOResponseHandler

### PR DESCRIPTION
**Pull request by mheck136**
Fix possible data race in FIFOResponseHandler.ServeHTTP by adding a
mutex.

Addresses #28

### CODE REVIEW

**Comment by migueleliasweb** [comment]
Hi @mheck136 , thanks for the PR! 

Could you also add the mutex to the `PaginatedReponseHandler`?

**Comment by mheck136** [comment]
I don't think that there is any risk of a data race for `PaginatedResponseHandler`. I can still add the mutex if you want me to.

**Comment by migueleliasweb** [comment]
> Hi @migueleliasweb, I don't think that there is any risk of a data race for `PaginatedResponseHandler`. I can still add the mutex if you want me to.

It's all good, let me double check a couple things and I will be right back with you.

**Comment by migueleliasweb** [comment]
Hi @mheck136 , yeah we probably won't need the mutex in the paginated handler for now.

Can you just merge the two `defer` statements into one? (using the last one where the index is incremented).

Then I can merge and create a new release :)

**Comment by mheck136** [comment]
@migueleliasweb, I'm not sure that's a good idea. I would keep the `defer srh.lock.Unlock()` right after the `Lock()`, because they are directly related to each other. This way it's also easier to maintain the right ordering of the deferred actions.
If you still want me to change it, I can do that. Please let me know.

**Comment by mheck136** [comment]
@migueleliasweb , how do you want to proceed with this PR?

**Comment by mheck136** [comment]
@migueleliasweb , I still think it would be best to keep the code as it is. When `defer srh.lock.Unlock()` is merged with `defer func()...` later on and the panic in line 40 triggers, the lock won't be released again, which should be avoided. Would be great if we could get this merged :)

**Comment by migueleliasweb** [comment]
Hi @mheck136 , sorry for the delay. Life has been pretty busy lately.

Let's merge this :+1:

**Pull request merged**
